apiVersion: v1
kind: Service
metadata:
  name: react-hello-world
  labels:
    app: react-hello-world
spec:
  clusterIP: None
  ports:
    - port: 80
      name: react-hello-world
  selector:
    app: react-hello-world
