apiVersion: v1
kind: Service
metadata:
  name: golang-gin-rest
  labels:
    app: golang-gin-rest
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: golang-gin-rest
  selector:
    app: golang-gin-rest
