apiVersion: v1
kind: Service
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  clusterIP: None
  ports:
    - port: 5000
      name: python-flask
  selector:
    app: python-flask
