apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: golang-hello-world
deploy:
  kubectl:
    manifests:
      - k8s/*
portForward:
- resourceType: deployment
  resourceName: golang-hello-world
  port: 8080

