apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: golang-hello-world
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
deploy:
  kubectl:
    manifests:
      - k8s/*
