apiVersion: v1
kind: Service
metadata:
  name: python-hello-world
  labels:
    app: python-hello-world
spec:
  clusterIP: None
  ports:
    - port: 5000
      name: python-hello-world
  selector:
    app: python-hello-world
