apiVersion: v1
kind: Service
metadata:
  name: golang-hello-world
  labels:
    app: golang-hello-world
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: golang-hello-world
  selector:
    app: golang-hello-world
